# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jhon Beltrán
# SEO purpose
title_separator: "|"
# Author
name: "Jhon Fredy Beltrán León"

locale: "es-CO"

email: jbeltranleon@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Bienvenidos a la gh-page de un estudiante de universidad publica y de plataforma online #Ucundinamarca #Platzi.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jbeltranleon
github_username:  jhonbeltran

# feed

atom_feed:
  path: "http://eepurl.com/dIiqZ5"

# Build settings
markdown: kramdown
# theme: minima
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include: ["_pages"]

# Pagination
paginate: 5 # amount of posts to show
paginate_path: /page:num/

repository: "jhonbeltran/jhonbeltran.github.io"

#Image Default teaser
teaser: /assets/images/teaser.jpg

breadcrumbs: true  # disabled by default

# Search menu
search: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true
      comments: true
